---
title: "How can you contribute?"
date: 2025-04-08
date-format: YYYY-MM-DD
draft: true
format:
  html:
    toc: true
    toc-expand: 2
---

If you have a dataset that you would like to register on the catalogue, the following process outlines how to do this.

# Before you start

## Requirements to contribute to the data catalogue

In order to contribute to the catalogue, the following criteria must be met:

-   **The dataset should be publicly available for researchers**. There are proprietary datasets that could in theory also be listed, however until the price statistics reproducibility project figures out the process for this, we request that only fully open datasets are registered. We encourage requests on valuable proprietary datasets, however these will not be catalogued until the process is flushed out.
-   **The dataset must be related to the price statistics discipline**. Price statisticians most typically track change in prices, such as through price index methods – thus the dataset should support this use case. Other use cases, such as for machine learning applications when it comes to classification, can also be submitted, but should be as close to the needs of the discipline as possible.
-   **Be of value to the discipline**. Many data catalogues that are too lax with the cataloguing process become filled with many datasets of incremental value. As a result, users struggle to find highly valuable datasets, which eventually causes a dropoff in use of the catalogue. To avoid this, the value of the dataset to researchers in the discipline should be clear. The reproducibility team will review and approve each proposed submission during each meeting.
-   **The contributor must document the dataset in full when the dataset is to be registered**. Having partially documented datasets on the catalogue will take away from user experience and will thus takeaway from the push to be open. A [Maturity model of registered datasets] is provided below to showcase how to document a dataset.
-   **The dataset should be real, although artificial and modified datasets are accepted if they are of value to reproducibility.** Specifically, synthetic datasets generated as part of a research process may not need to be registered if they can be reproduced through code published with the research, in which case we recommend that the code that generated it be made publicly available as part of that research projects' [research compendium](https://un-task-team-for-scanner-data.github.io/reproducibility-project/docs/reproducibility-guidance/intro.html).
    -   Some synthetic/artificial datasets may be proposed, such as if the artificial dataset has become of high value and is used everywhere **as if** its a real dataset (such as the Turvey dataset).
-   **The dataset is already published somewhere easy to download and in a machine readable format**. Make sure that users can download and use the dataset easily. Several options for hosting a dataset are possible (see next section on where to host datasets).

## Where to host the dataset

As the price statistics data catalogue describes datasets already hosted elsewhere (in other words it is not a data repository), the first step is to host the dataset somewhere. This is fundamentally up to the researcher and the institution they work at. Ideally a data repository is used that mints a Digitial Object Identifier (DOI) so that the dataset can be easily cited and found. Data repositories often allow a researcher to host private datasets and lock down access but still create a DOI. Regardless of where, the DOI should be ready when the dataset is registered in the catalogue so that researchers can find the dataset itself and know how to cite the dataset.

Read more about [data repositories in the Turing Way](https://book.the-turing-way.org/reproducible-research/rdm/rdm-repository#rr-rdm-repository-select).

# How to register a dataset on the catalogue?

Once the above aspects are considered, a dataset can be registered to the catalogue.

The catalogue uses the open-source python package [`datacontract-cli`](https://cli.datacontract.com/) to render the dataset record as a static html site. Each dataset originally entered as a `yaml` file following the structure of this package is saved in the `/datasets/` directory of this GitHub repository. Contributors have the following options:

### Request to add a new dataset yourself (or modify a dataset that exists):

The best way is to directly propose a dataset and start the process of registering it (such as by fully describing the dataset).

1.  Fork [the catalogue repo](https://github.com/UN-Task-Team-for-Scanner-Data/price-stats-data-catalogue) and mock up a new dataset in the `/datasets/` directory of your fork.
2.  Submit a PR to request that we add it to the catalogue. Please tag it to the [dataset](https://github.com/UN-Task-Team-for-Scanner-Data/price-stats-data-catalogue/labels/dataset) label.
3.  We will review your request and coordinate with you as appropriate (such as if we need more info) or help further flush out the metadata so that the dataset is well defined before it is published.

When we are ready, we will either merge your PR and thus register your dataset or reject the dataset if it is not appropriate.

### Request that we add a new dataset:

You could also just give us a ping to let us know that a good dataset exists and we can review and register it when we get a chance.

1.  Create [a new issue](https://github.com/UN-Task-Team-for-Scanner-Data/price-stats-data-catalogue/issues/new) and describe the dataset you wish that we register. Include the relevant details that we can use to find out more about the dataset. Please also tag the issue with the [dataset](https://github.com/UN-Task-Team-for-Scanner-Data/price-stats-data-catalogue/labels/dataset) label.

# Maturity model of registered datasets {#maturity-model}

As not all datasets can be completed to the same level, we've broken up the structure into a maturity model to aspire to for each dataset record, starting from the benchmark to the gold standard.

## Level 1

This level sets a bare minimum a dataset needs to have to be registered to the catalogue

-   [ ] The dataset has a basic description to introduce it to any users in the discipline
-   [ ] The data model (structure of the data and each variable) is documented
-   [ ] The dataset is available openly and the data file format is anything that is machine readable (for instance proprietary or language specific data formats are fine, however a pdf is not) is referenced.
-   [ ] The license (or at minimum terms of the use of the dataset) is listed.
-   [ ] Information on how to cite the dataset is available

## Level 2

Level 2 implies a higher level of maturity to simplify the process for data

-   [ ] The dataset is stored in an open file format
-   [ ] Dataset quality considerations and detailed nuances of the data are discussed

## Level 3

This implies a 'gold standard' for a dataset

-   [ ] The dataset is made available in a data repository (such as Zenodo) that mints a DOI. This DOI is listed as part of the dataset.
-   [ ] A data paper detailing the dataset is available and linked. Alternatively, a blog can also be written on the project site to introduce the dataset with the dataset owner.