---
title: "How to cite open data"
date: 2025-04-28
date-format: YYYY-MM-DD
format:
  html:
    toc: true
    toc-expand: 2
---

Citing an open dataset for a research project is straightforward if it is
archived in an open research repository like [Zenodo](https://zenodo.org/). In
this case it will have the relevant metadata, along with a DOI, to make it
easily citeable, even if access to these data is restricted. Unfortunately open
datasets do not always reside in a repository like Zenodo.
A common place for open datasets in statistics, and in particular price
statistics, is as part of an R package on CRAN. Citing these datasets is not
difficult---all CRAN packages have a DOI and are easily cited---but, as part of
a package, data are more difficult to access.

## Example: {PriceIndices}

The {PriceIndices} R package comes with several datasets that can be useful for
comparing different index-number methods. Citing these data is easy because R
packages are highly citeable.

```
@Manual{,
  title = {PriceIndices: Calculating Bilateral and Multilateral Price Indexes},
  author = {Jacek Białek},
  year = {2025},
  doi = {10.32614/CRAN.package.PriceIndices},
  url = {https://cran.r-project.org/package=PriceIndices},
  note = {R package version 0.2.3}
}
```

Using these data is easy enough with R. Simply install the package and the
datasets become available from within R.