---
title: "Open a dataset and registering it to the catalogue"
date: 2025-04-28
date-format: YYYY-MM-DD
format:
  html:
    toc: true
    toc-expand: 2
---

If you have a dataset that you want to register on the catalogue (whether you own it or you simply know a good one for us to include), we'd like to hear from you!

## Some basic ideas on open data

Data should ideally be [Findable, Accessible, Interoperable, and Reusable (i.e. FAIR)](https://www.go-fair.org/fair-principles/). In essence, it is best that it is shared in a data repository[^1] that creates a Digital Object Identifiers (or DOI) for the data. This makes it easy for anyone to find the data. Data repositories also support hosting a lot of information and metadata about the dataset and even make it possible to host private datasets where only metadata is available to the wider public. If the dataset needs to be expanded regularly, using a repository will make it easy for others to find both the parent dataset and understand what version of the historic dataset was used.

[^1]: Read more about [data repositories in the Turing Way](https://book.the-turing-way.org/reproducible-research/rdm/rdm-repository#rr-rdm-repository-select).

::: callout-tip
## Interim recommendation: Use a data repository (if you can) to host open data

The project is investigating longer term solutions, however for now, we recommend that an option researchers consider is using a general purpose data repository, although you should always check with your institution first.
:::

## A quick process to follow to register the dataset on the catalogue.

Once a dataset is hosted somewhere such as a data repository and the catalogue can cite it, we can register the dataset to the catalogue. In a nutshell, it is as simple as making a new dataset record in the `/datasets/` folder of the [Catalogue GitHub repository](https://github.com/UN-Task-Team-for-Scanner-Data/price-stats-data-catalogue)!

A slightly more technical process is outlined in the [contributing guidance of the data catalogue](https://github.com/UN-Task-Team-for-Scanner-Data/price-stats-data-catalogue/blob/main/CONTRIBUTING.md).