---
title: "How to reference digital objects you create"
subtitle: "Recommendation for a structured approach to citing digitial objects in papers"
date: 2025-04-28
date-modified: 2025-11-25
format:
  html:
    toc: true
    toc-expand: 3

categories:
  - citation
  - findability
---

When writing a paper, a structured approach to citing your research compendium is useful as it creates a coherent approach among the discipline.

## Proposed sensible default

Inspired by [the FAIR research code approach](https://www.nature.com/articles/s41597-022-01710-x#data-availability), we recommend including references to the digital byproducts made available alongside the research (i.e. the research compendium and any new datasets created) in the following manner at the end of your paper.

Add two headers just after the conclusion and before the references section:

> *... conclusion of the paper*
>
> ## Data availability
>
> *Summarize where datasets created as part of the paper are published. This could be on a data repository like Zenodo for instance.*
>
> ## Code availability
>
> *Add link to the GitHub repository where the research compendium is published.*
>
> ## References
>
> *... rest of the references*

## What about datasets you use or other people's code?

The best place to reference others' code or open datasets is in the bibliography. Ideally these should have a Digitial Object Identifier (or DOI) so they are unique and can be easily found. There may be harder cases, which are detailed out in more detail in separate articles:

-   [How to cite data](citing-data.qmd).
-   [How to cite others' code](citing-code.qmd).